apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: {{ .Values.auth.hpa.minReplicas }}
  maxReplicas: {{ .Values.auth.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.auth.hpa.targetCpuPercentage }}
