version: "3.9"
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    image: nickdodson/auth-service:${GITHUB_VERSION_TAG}
    
  v2:
    container_name: v2
    build:
      context: .
      dockerfile: ./packages/v2/Dockerfile
    image: nickdodson/v2-service:${GITHUB_VERSION_TAG}

