version: "3.9"
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    image: nickdodson/auth-service:v1.14.20

  router:
    container_name: router
    build:
      context: .
      dockerfile: ./packages/graphql-api/Dockerfile
    image: nickdodson/router-service:v1.14.20

  spaces:
    container_name: spaces
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/spaces/Dockerfile
    image: nickdodson/spaces-service:v1.14.20

  contests:
    container_name: contests
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/contests/Dockerfile
    image: nickdodson/contests-service:v1.14.20

  submit:
    container_name: submit
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/submit/Dockerfile
    image: nickdodson/submit-service:v1.14.20

  vote:
    container_name: vote
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/vote/Dockerfile
    image: nickdodson/vote-service:v1.14.20

  user:
    container_name: user
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/user/Dockerfile
    image: nickdodson/user-service:v1.14.20

  tweet:
    container_name: tweet
    build:
      context: .
      dockerfile: ./packages/tweet/Dockerfile
    image: nickdodson/tweet-service:v1.14.20
    
  v2:
    container_name: v2
    build:
      context: .
      dockerfile: ./packages/v2/Dockerfile
    #image: nickdodson/v2-service:v1.14.20

