federation_version: 2
subgraphs:
  spaces:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../../subgraphs/spaces/schema.graphql
  contests:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ../../subgraphs/contests/schema.graphql
  submit:
    routing_url: http://localhost:4004/graphql
    schema:
      file: ../../subgraphs/submit/schema.graphql
  vote:
    routing_url: http://localhost:4005/graphql
    schema:
      file: ../../subgraphs/vote/schema.graphql
  user:
    routing_url: http://localhost:4006/graphql
    schema:
      file: ../../subgraphs/user/schema.graphql
