federation_version: 2
subgraphs:
  spaces:
    routing_url: http://localhost:5003
    schema:
      file: ../../subgraphs/spaces/schema.graphql
  contests:
    routing_url: http://localhost:5004
    schema:
      file: ../../subgraphs/contests/schema.graphql
  submit:
    routing_url: http://localhost:5005
    schema:
      file: ../../subgraphs/submit/schema.graphql
  vote:
    routing_url: http://localhost:5006
    schema:
      file: ../../subgraphs/vote/schema.graphql
  user:
    routing_url: http://localhost:5007
    schema:
      file: ../../subgraphs/user/schema.graphql
