federation_version: 2
subgraphs:
  spaces:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ../../subgraphs/spaces/schema.graphql
  contests:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../../subgraphs/contests/schema.graphql
  submissions:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ../../subgraphs/submissions/schema.graphql
