apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    #nginx.ingress.kubernetes.io/cors-allow-origin: "TODO"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Cookie"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: production-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:

      - path: /api/auth/
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 8080

      - path: /api/media/
        pathType: Prefix
        backend:
          service:
            name: media
            port:
              number: 8080

      - path: /api/graphql
        pathType: Prefix
        backend:
          service:
            name: router
            port:
              number: 8080