apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces
spec:
  replicas: {{ .Values.spaces.replicaCount }}
  selector:
    matchLabels:
      app: spaces
  template:
    metadata:
      labels:
        app: spaces
    spec:
      containers:
      - name: spaces
        image: "{{ .Values.spaces.image.repository }}:{{ .Values.image_version_tag }}"
        resources:
          requests:
            cpu: "20m"
        env:
          - name: SPACE_SERVICE_PORT
            value: "8080"
        envFrom:
          - secretRef:
              name: {{ .Values.sealedSecretName }}

---

apiVersion: v1
kind: Service
metadata:
  name: spaces
spec:
  type: ClusterIP
  selector:
    app: spaces
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spaces-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spaces
  minReplicas: {{ .Values.spaces.hpa.minReplicas }}
  maxReplicas: {{ .Values.spaces.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.spaces.hpa.targetCpuPercentage }}
