apiVersion: apps/v1
kind: Deployment
metadata:
  name: submit
spec:
  replicas: {{ .Values.submit.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
  selector:
    matchLabels:
      app: submit
  template:
    metadata:
      labels:
        app: submit
    spec:
      containers:
      - name: submit
        image: "{{ .Values.submit.image.repository }}:{{ .Values.image_version_tag }}"

        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 2
          httpGet:
            path: /?query=%7B__typename%7D
            port: 8080
            httpHeaders:
            - name: apollo-require-preflight
              value: "true"

        resources:
          requests:
            cpu: "20m"
        env:
          - name: SUBMIT_SERVICE_PORT
            value: "8080"
        envFrom:
          - secretRef:
              name: {{ .Values.sealedSecretName }}

---

apiVersion: v1
kind: Service
metadata:
  name: submit
spec:
  type: ClusterIP
  selector:
    app: submit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: submit-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: submit
  minReplicas: {{ .Values.submit.hpa.minReplicas }}
  maxReplicas: {{ .Values.submit.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.submit.hpa.targetCpuPercentage }}
