apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: {{ .Values.tweet.replicaCount }}
  selector:
    matchLabels:
      app: tweet
  template:
    metadata:
      labels:
        app: tweet
    spec:
      containers:
      - name: tweet
        image: "{{ .Values.tweet.image.repository }}:{{ .Values.image_version_tag }}"
        resources:
          requests:
            cpu: "20m"
        env:
          - name: TWEET_SERVICE_PORT
            value: "8080"
        envFrom:
          - secretRef:
              name: {{ .Values.sealedSecretName }}

---

apiVersion: v1
kind: Service
metadata:
  name: tweet
spec:
  type: ClusterIP
  selector:
    app: tweet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tweet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tweet
  minReplicas: {{ .Values.tweet.hpa.minReplicas }}
  maxReplicas: {{ .Values.tweet.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.tweet.hpa.targetCpuPercentage }}
