apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: {{ .Values.vote.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: "{{ .Values.vote.image.repository }}:{{ .Values.image_version_tag }}"
       
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 2
          httpGet:
            path: /?query=%7B__typename%7D
            port: 8080
            httpHeaders:
            - name: apollo-require-preflight
              value: "true"

        resources:
          requests:
            cpu: "20m"
        env:
          - name: VOTE_SERVICE_PORT
            value: "8080"
        envFrom:
          - secretRef:
              name: {{ .Values.sealedSecretName }}

---

apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: {{ .Values.vote.hpa.minReplicas }}
  maxReplicas: {{ .Values.vote.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.vote.hpa.targetCpuPercentage }}
