
ingress:
  host: hub.uplink.wtf


sealedSecretName: production-sealed-secret

auth:
  image:
    repository: nickdodson/auth-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80
    
v2:
  image:
    repository: nickdodson/v2-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80