ingress:
  host: staging.hub.uplink.wtf

sealedSecretName: staging-sealed-secret

auth:
  image:
    repository: nickdodson/auth-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 1
    targetCpuPercentage: 80

v2:
  image:
    repository: nickdodson/v2-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 1
    targetCpuPercentage: 80