auth:
  image:
    repository: nickdodson/auth-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCpuPercentage: 80
    
router:
  image:
    repository: nickdodson/router-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCpuPercentage: 80

space:
  image:
    repository: nickdodson/spaces-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCpuPercentage: 80

ingress:
  host: staging.hub.uplink.wtf


sealedSecretName: staging-sealed-secret