
ingress:
  host: hub.uplink.wtf


sealedSecretName: production-sealed-secret

auth:
  image:
    repository: nickdodson/auth-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80
    
router:
  image:
    repository: nickdodson/router-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80

spaces:
  image:
    repository: nickdodson/spaces-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80


contests:
  image:
    repository: nickdodson/contests-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80
    
submit:
  image:
    repository: nickdodson/submit-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80

vote:
  image:
    repository: nickdodson/vote-service
  replicaCount: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCpuPercentage: 80

user:
  image:
    repository: nickdodson/user-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCpuPercentage: 80

tweet:
  image:
    repository: nickdodson/tweet-service
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 1
    targetCpuPercentage: 80
