apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth

patches:
- path: deployment.yaml
  target:
    kind: Deployment
- path: service.yaml
  target:
    kind: Service
