version: "3.9"
services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./packages/proxy/Dockerfile
    ports:
      - "8080:80"
      - "443:443"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/auth:/usr/src/app/packages/auth
        # - auth_node_modules:/usr/src/app/packages/auth/node_modules
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  media:
    container_name: media
    build:
      context: .
      dockerfile: ./packages/media/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./packages/media:/usr/src/app
  graphql:
    container_name: graphql
    build:
      context: .
      dockerfile: ./packages/graphql-api/Dockerfile
    ports:
      - "4001:4000"
  spaces:
    container_name: spaces
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/spaces/Dockerfile
    ports:
      - "4002:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/spaces/src:/usr/src/app/packages/spaces/src

  contests:
    container_name: contests
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/contests/Dockerfile
    ports:
      - "4003:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/contests/src:/usr/src/app/packages/contests/src
        #- contests_node_modules:/usr/src/app/packages/contests/node_modules
  submissions:
    container_name: submissions
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/submissions/Dockerfile
    ports:
      - "4004:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/submissions/src:/usr/src/app/packages/submissions/src
        #- submissions_node_modules:/usr/src/app/packages/submissions/node_modules

volumes:
  spaces_node_modules:
    #auth_node_modules:
  contests_node_modules:
  submissions_node_modules:
