version: '3.9'
services:
  router:
    container_name: router
    build: ./test-router
    ports:
      - "4000:4000"
  spaces:
    container_name: spaces
    build: ./subgraphs/spaces
    ports:
      - "4001:4000"
    volumes:
      - ./subgraphs/spaces:/usr/src/app
  contests:
    container_name: contests
    build: ./subgraphs/contests
    ports:
      - "4002:4000"
    volumes:
      - ./subgraphs/contests:/usr/src/app
  submissions:
    container_name: submissions
    build: ./subgraphs/submissions
    ports:
      - "4003:4000"
    volumes:
      - ./subgraphs/submissions:/usr/src/app
