version: '3.9'
services:
  spaces:
    container_name: spaces
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/spaces/Dockerfile
    ports:
      - "4002:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/spaces:/usr/src/app/packages/spaces
      - spaces_node_modules:/usr/src/app/packages/spaces/node_modules

volumes:
  spaces_node_modules:
