version: '3.9'
services:
  organizations:
    container_name: organizations
    build: ./subgraphs/organizations
    ports:
      - "4001:4000"
    volumes:
      - ./subgraphs/organizations:/usr/src/app
