version: '3.9'
services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./packages/proxy/Dockerfile
    ports:
      - "8080:80"
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/auth:/usr/src/app/packages/auth
        # - auth_node_modules:/usr/src/app/packages/auth/node_modules
  media:
    container_name: media
    build:
      context: .
      dockerfile: ./packages/media/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./packages/media:/usr/src/app
  graphql:
    container_name: graphql
    build:
      context: .
      dockerfile: ./packages/graphql-api/Dockerfile
    ports:
      - "4001:4000"
  spaces:
    container_name: spaces
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/spaces/Dockerfile
    ports:
      - "4002:4000"
    volumes:
        - ./packages/graphql-api/subgraphs/spaces/src:/usr/src/app/packages/spaces/src
          #- spaces_node_modules:/usr/src/app/packages/spaces/node_modules

  contests:
    container_name: contests
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/contests/Dockerfile
    ports:
      - "4003:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/contests:/usr/src/app/packages/contests
        #- contests_node_modules:/usr/src/app/packages/contests/node_modules
  submissions:
    container_name: submissions
    build:
      context: .
      dockerfile: ./packages/graphql-api/subgraphs/submissions/Dockerfile
    ports:
      - "4004:4000"
    volumes:
      - ./packages/graphql-api/subgraphs/submissions:/usr/src/app/packages/submissions
        #- submissions_node_modules:/usr/src/app/packages/submissions/node_modules

volumes:
  spaces_node_modules:
    #auth_node_modules:
  contests_node_modules:
  submissions_node_modules:
