version: '3.9'
services:
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - "8080:80"
  auth:
    container_name: auth
    build: ./auth
    ports: 
      - "5000:5000"
    volumes:
      - ./auth:/usr/src/app
  media:
    container_name: media
    build: ./media
    ports:
      - "5001:5000"
    volumes:
      - ./media:/usr/src/app
  graphql:
    container_name: graphql
    build: ./graphql-api
    ports:
      - "4001:4000"
  spaces:
    container_name: spaces
    build: ./graphql-api/subgraphs/spaces
    ports:
      - "4002:4000"
    volumes:
      - ./graphql-api/subgraphs/spaces:/usr/src/app
  contests:
    container_name: contests
    build: ./graphql-api/subgraphs/contests
    ports:
      - "4003:4000"
    volumes:
      - ./graphql-api/subgraphs/contests:/usr/src/app
  submissions:
    container_name: submissions
    build: ./graphql-api/subgraphs/submissions
    ports:
      - "4004:4000"
    volumes:
      - ./graphql-api/subgraphs/submissions:/usr/src/app

