apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spaces-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spaces
  minReplicas: {{ .Values.spaces.hpa.minReplicas }}
  maxReplicas: {{ .Values.spaces.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.spaces.hpa.targetCpuPercentage }}
