on:
  pull_request:
    types:
      - closed
    branches:
      - main


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: uplink-hub-cluster
  GKE_ZONE: us-east4-a


jobs:
  build:
      name: Build
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.sha }}
            fetch-depth: 0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
        - name: Bump version and push tag
          id: bump_tag
          uses: anothrNick/github-tag-action@1.64.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: minor

        - name: Build and push docker images
          run: |
            export GITHUB_VERSION_TAG=${{ steps.bump_tag.outputs.new_tag }}
            docker-compose -f uplink-hub/docker-compose.yaml build
            docker-compose -f uplink-hub/docker-compose.yaml push


  deploy-staging:
    name: Deploy to Staging
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      
      - name: init gcloud CLI
        uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: connect to GKE
        uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ secrets.GKE_PROJECT }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: update image tags and deploy
        run: |
          cd uplink-hub/k8s
          (cd overlays/staging/auth && kustomize edit set image nickdodson/auth-service:${{needs.build.steps.bump_tag.outputs.new_tag}})
          kubectl apply -k overlays/staging
          kubectl 
          kubectl get svc -n staging -o wide
          kubectl get deploy -n staging -o wide
          kubectl get deploy -n staging -o wide
