name: Staging CI/CD

on:
  push:
    branches:
      - staging

jobs:
  auth_service:
    runs-on: ubuntu-latest
    if: contains(toJSON(github.event.commits.*.modified), 'packages/auth')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: auth_create_tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_PREFIX: auth-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth
        run: |
          docker-compose build auth
          docker tag auth:latest nickdodson/auth-service:${{ steps.auth_create_tag.outputs.new_tag }}
          docker push nickdodson/auth-service:${{ steps.auth_create_tag.outputs.new_tag }}
