name: Staging CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      auth: ${{ steps.filter.outputs.auth }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: detect changes
      uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        base: ${{ github.ref_name }}
        filters: |
          auth:
            - 'uplink-hub/packages/auth/**'
            
  auth_service:
    needs: changes
    if: ${{ needs.changes.outputs.auth == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: auth_create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_PREFIX: auth-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth
        run: |
          docker-compose -f uplink-hub/docker-compose.yaml build auth
          docker images
          echo "New tag: ${{ steps.auth_create_tag.outputs.new_tag }}"
          docker tag uplink-hub_auth:latest nickdodson/auth-service:${{ steps.auth_create_tag.outputs.new_tag }}
          docker push nickdodson/auth-service:${{ steps.auth_create_tag.outputs.new_tag }}


  archive-images:
    needs: auth_service
    name: Create image archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get auth tag
        id: auth_get_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          TAG_PREFIX: auth-
      - name: Push to env
        run: |
          echo "DOCKER_AUTH_IMG=${{ steps.auth_get_tag.outputs.tag }}" > ./uplink-hub/tags.env
    


  pre-release:
    name: Pre Release
    needs: archive-images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release Tag
      id: create_release_tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        TAG_PREFIX: staging-
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_release_tag.outputs.new_tag }}
        release_name: Release ${{ steps.create_release_tag.outputs.new_tag }}
        draft: false
        prerelease: true
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./uplink-hub/tags.env
        asset_name: tags.env
        asset_content_type: text/plain 


