name: Staging CI/CD

on:
  push:
    branches: [ staging ]

jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short sha
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker images
        run: |
          docker-compose -f uplink-hub/docker-compose.yaml -e GITHUB_SHA_TAG=${{ env.SHORT_SHA }}  build
          echo "SHA TAG: ${{ env.SHORT_SHA }}"
          docker-compose -f uplink-hub/docker-compose.yaml -e GITHUB_SHA_TAG=${{ env.SHORT_SHA }} push
          
      - name: Bump version and push tag
        id: create_branch_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
